[source]

frequency = 100_000_000
gain = 30
rate = 1_000_000
args = ""

[[bookmarks]]
name = "Radio 1"
frequency = 92_000_000

[[bookmarks]]
name = "Radio 2"
frequency = 92_000_000

[[bookmarks]]
name = "Radio 3"
frequency = 92_000_000